"""Generate the TOML blob to paste into Streamlit Cloud's secrets UI.

Reads from local .env + secrets/*.json and writes streamlit-secrets.toml (gitignored).
Run this any time you update credentials, then re-paste into Streamlit Cloud.
"""
from pathlib import Path

ROOT = Path(__file__).parent

# --- Read .env (simple parser, ignoring comments) ---
env: dict[str, str] = {}
for line in (ROOT / ".env").read_text().splitlines():
    s = line.strip()
    if not s or s.startswith("#") or "=" not in s:
        continue
    k, _, v = s.partition("=")
    env[k.strip()] = v.strip().strip('"').strip("'")

# --- Read OAuth files ---
oauth_client = (ROOT / "secrets" / "oauth-client.json").read_text().rstrip()
ga4_token = (ROOT / "secrets" / "ga4-token.json").read_text().rstrip()

# Keys we want to push to Streamlit Cloud (the dashboard uses these)
KEYS = [
    "GA4_PROPERTY_ID",
    "GSC_SITE_URL",
    "SHEETS_NEWSLETTER_FEEDBACK_ID",
    "STRIPE_SECRET_KEY",
    "GOOGLE_ADS_DEVELOPER_TOKEN",
    "GOOGLE_ADS_CUSTOMER_ID",
    "GOOGLE_ADS_LOGIN_CUSTOMER_ID",
    "BEEHIIV_API_KEY",
    "BEEHIIV_PUB_CLEARER_THINKING",
    "BEEHIIV_PUB_12_LEVERS",
    "BEEHIIV_PUB_TRANSPARENT_REPLICATIONS",
]

lines = ["# Generated by generate_streamlit_secrets.py — paste this into Streamlit Cloud's Secrets UI."]
missing = []
for k in KEYS:
    v = env.get(k, "")
    if not v:
        missing.append(k)
        continue
    # TOML basic strings work for simple values; escape backslash and double-quote
    escaped = v.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'{k} = "{escaped}"')

# Multi-line JSON blobs use TOML triple-quoted strings
lines.append("")
lines.append('OAUTH_CLIENT_JSON = """')
lines.append(oauth_client)
lines.append('"""')
lines.append("")
lines.append('GOOGLE_TOKEN_JSON = """')
lines.append(ga4_token)
lines.append('"""')

out_path = ROOT / "streamlit-secrets.toml"
out_path.write_text("\n".join(lines) + "\n")

print(f"Wrote {out_path.name} ({out_path.stat().st_size} bytes)")
if missing:
    print(f"Missing values for: {', '.join(missing)} (lines were skipped)")
